server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  application:
    name: blog-admin
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  profiles:
    active: druid
  data:
    redis:
      host: 192.168.1.110
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      password: qingfeng
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qf.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
## mybatis-plus配置
mybatis-plus:
  ## plus的实体别名包，不需要写出实体类的完整路径，只需要写出类名即可
  type-aliases-package: com.qf.web.domain.entity
  ## mybatis  mapper.xml的位置
  mapper-locations: classpath:mapper/*Mapper.xml
  ## mybatis  config的配置文件位置

  config-location: classpath:mybatis/mybatis-config.xml
  ## 全局配置
  global-config:
    db-config:
      ## id生成策略为雪花id
      id-type: assign_id
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
    ## 不启用mybatis-plus的banner
    banner: false
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: qf123
  # 令牌有效期（默认30分钟）
  expireTime: 3000000